version: '3'

services:
  database:
    image: 'bitnami/mysql:latest'    
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=augen
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mysql_data:/bitnami/mysql/data'

volumes:
  mysql_data:
    driver: local